# actuator end-points should be served from a different port than the API/web content
management:
  port: 8008
  security:
    enabled: false

saml:
  # SAML keystore path: file:/some/path/saml.jks
  key-store-file: ${rdw.admin.keystore.path}
  key-store-password: ${rdw.admin.keystore.password}
  private-key-entry-alias: ${rdw.admin.keystore.alias}
  private-key-entry-password: ${rdw.admin.keystore.entry.password}
  idp-metadata-url: ${rdw.admin.idp}
  sp-entity-id: ${rdw.admin.entityId}
  # SAML settings when hosting behind a load balancer or reverse proxy
  load-balance:
    enabled: false
    scheme: https
    hostname:
    context-path: /
    port: 8080
    include-server-port: false

server:
  # straw-man values for restricting resource utilization
  tomcat:
    max-connections: 100
    max-threads: 20

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse?useSSL=false&useLegacyDatetimeCode=false&characterEncoding=utf8
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    initialize: false
  http:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  cache:
    type: SIMPLE
    cache-names: permissionsByRole

    # Force the (rabbit) queues to be created when posting messages so, even if
    # there are no consumers running, the messages will not get lost. Routing is
    # dynamic based on content but there is no way to do that here so we must
    # explicitly declare all possible output channels here (EXAM, PACKAGE, etc.).
    # The group names must be coordinated with the consumer application configs.
  cloud:
    stream:
      bindings:
        output:
          destination: GROUPS
          group: default

# spring auto-configured aws defense
cloud:
  aws:
    # there must be a default region when running locally
    region:
      auto: false
      static: us-west-2
    # disable CloudFormation stuff
    stack:
      auto: false
    credentials:
      instance-profile: false

# Needed for access to S3

# Location of import archive.
archive:
  root: file:///tmp/

application:
  state: CA

permissionservice:
  component: Reporting
  endpoint: http://perm-web-deployment.sbtds.org:8080/rest

app:
  home-url: /

  # google analytics configuration
  analytics:
    trackingId: ${rdw.admin.analytics.trackingId:}