# actuator end-points should be served from a different port than the API/web content
management:
  port: 8008
  security:
    enabled: false

saml:
  # SAML keystore path: file:/some/path/saml.jks
  key-store-file: ${rdw.reporting.keystore.path}
  key-store-password: ${rdw.reporting.keystore.password}
  private-key-entry-alias: ${rdw.reporting.keystore.alias}
  private-key-entry-password: ${rdw.reporting.keystore.entry.password}
  idp-metadata-url: ${rdw.reporting.idp}
  sp-entity-id: ${rdw.reporting.entityId}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse?useSSL=false&useLegacyDatetimeCode=false
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    initialize: false
  http:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  cache:
    type: SIMPLE
    cache-names: permissionsByRole, internalTranslationsByCode

  cloud:
    stream:
      bindings:
        output:
          destination: exam_report_pdf
          group: default

cloud:
  aws:
    credentials:
      #AWS credentials are necessary if reading assessment files from S3
      accessKey: ${rdw.aws.access.key:}
      secretKey: ${rdw.aws.secret.key:}
      instance-profile: false
    region:
      auto: false
      static: us-west-2
    # disable CloudFormation stuff
    stack:
      auto: false

application:
  state: CA

permissionservice:
  component: Reporting
  endpoint: ${rdw.permission.service}

app:
  # google analytics configuration
  analytics:
    trackingId: ${rdw.reporting.analytics.trackingId:}
