sql:
  admin:
    findWarehouseImports: >-
      SELECT i.id, i.digest FROM import i limit 10;

  district:
    findAllIds: >-
      select natural_id, id
      from district
      where natural_id in (:naturalIds)

  school:
    findAllIds: >-
      select natural_id, id
      from school
      where natural_id in (:naturalIds)

    findAll: >-
      select name, id
      from school
      where (1=:statewide or district_id in (:district_ids) or id in (:school_ids))

  status:
    readTest: >-
      SELECT ist.name FROM import_status ist
