sql:
  admin:
    findWarehouseImports: >-
      SELECT i.id, i.digest FROM import i limit 10;

  district:
    findAllIds: >-
      select natural_id, id
      from district
      where natural_id in (:naturalIds)

  school:
    findAllIds: >-
      select natural_id, id
      from school
      where natural_id in (:naturalIds)

    findAll: >-
      select name, id
      from school
      where (1=:statewide or district_id in (:district_ids) or id in (:school_ids))

  status:
    readTest: >-
      SELECT ist.name FROM import_status ist

  student_group_batch:
    create: >-
      INSERT INTO upload_student_group_batch (status, digest, creator, message)
        VALUES (:status, :digest, :creator, :message)

    findOne: >-
      SELECT * FROM upload_student_group_batch WHERE id=:id

    findOneByDigest: >-
      SELECT * FROM upload_student_group_batch WHERE digest=:digest LIMIT 1

    sqlFindByCreator: >-
      SELECT * FROM upload_student_group_batch WHERE creator=:creator